server:
  port: 8080
spring:
  main:
    banner-mode: off
  #redis相关配置
  redis:
    database: 5
    # 配置redis的主机地址，需要修改成自己的
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000
  datasource:
    url: jdbc:mysql://localhost:3306/springbootjpatest?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  # 配置mapper的扫描路径
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置实体类的扫描路径
  type-aliases-package: com.example.springsercuitydemo.entity
  global-config:
    banner: false
    # 配置主键生成策略
    db-config:
      id-type: auto
  configuration:
    # 配置驼峰命名规则
    map-underscore-to-camel-case: true
    
   